# Generated by Django 5.2.8 on 2025-11-19 22:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
