# Generated by Django 5.2.6 on 2025-11-20 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_salas', '0002_logadmin_alter_reserva_fecha_hora_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logadmin',
            options={'ordering': ['-fecha']},
        ),
    ]
